version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - '8000:8000'
  mongo:
    image: mongo:5.0.7
    restart: always
    command: mongod --port 27019
    ports:
      - '27019:27019'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
